name: Test Dev Environment Setup

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: macos-latest
    defaults:
      run:
        shell: zsh {0}
    steps:
      - uses: actions/checkout@v4

      - run: ./01_bootstrap.sh

      - name: Upload verification artifacts
        uses: actions/upload-artifact@v4
        with:
          name: setup-verification
          path: artifacts/
          retention-days: 5